In [1]:
import numpy as np
import pandas as pd
import sys

In [2]:
dataset = pd.read_csv("Train.csv",encoding='utf-8')

In [3]:
dataset.head(n=10)

feature_1  feature_2  feature_3  feature_4  feature_5      target
0   0.293416  -0.945599  -0.421105   0.406816   0.525662  -82.154667
1  -0.836084  -0.189228  -0.776403  -1.053831   0.597997  -48.897960
2   0.236425   0.132836  -0.147723   0.699854  -0.187364   77.270371
3   0.175312   0.143194  -0.581111  -0.122107  -1.292168   -2.988581
4  -1.693011   0.542712  -2.798729  -0.686723   1.244077  -37.596722
5  -1.055329  -0.874807   0.580753  -0.773541   1.070888 -122.405263
6  -0.824707   0.499427   1.293281  -0.240671  -0.419136    1.413741
7  -1.936602   0.583708  -0.521135  -0.631724  -1.030729  -13.306543
8   0.647431  -0.265401   0.327080   0.457829  -1.757592  -25.754698
9  -1.133029  -0.839132  -0.547809   0.551768  -0.639173  -57.077754

In [4]:
X = dataset.values[:,:5]
Y = dataset.target
print(X.shape)
Y = Y.values.reshape((-1,1))
print(Y.shape)
print(X.shape)

#Normalize
X= (X-X.mean())/X.std()
ones = np.ones((X.shape[0],1))
X = np.hstack((ones,X))
print(X.shape)
X[:,:5]

(1600, 5)
(1600, 1)
(1600, 5)
(1600, 6)


array([[ 1.        ,  0.31139642, -0.92093003, -0.3992678 ,  0.42418404],
       [ 1.        , -0.81200658, -0.16864243, -0.75264729, -1.02857829],
       [ 1.        ,  0.25471295,  0.15168305, -0.12736142,  0.71564009],
       ...,
       [ 1.        ,  1.05810433, -0.87478823,  1.74062205, -1.84139222],
       [ 1.        , -1.24275748,  0.01453923,  1.8672047 , -1.05496863],
       [ 1.        , -1.85426585, -0.8252779 , -1.42486653,  0.50553954]])

In [5]:
def hypothesis(X,theta):
    hx = np.dot(X,theta)
    return hx
    

In [46]:
def error(X,Y,theta):
    m = X.shape[0]
    error = 0
    
    for i in range(m):
        hx = hypothesis(X[i],theta)
        error += (hx-Y[i])**2 
    return error/(2*m)

def gradient(X,Y,theta):
    grad = np.zeros((X.shape[1]))
    m = X.shape[0]
    n = X.shape[1]
    for j in range(n):
        for i in range(m):
            hx = hypothesis(X[i],theta)
            grad[j] += ((Y[i] - hx)*X[i][j]) 
    return grad

def algo(X,Y,learning_rate=0.001):
    theta = np.ones((X.shape[1]))
    error_list = []
    itr = 0
    max_itr = X.shape[0]
    while(itr<max_itr):
        grad = gradient(X,Y,theta)
        e = error(X,Y,theta)
        error_list.append(e)
        theta = theta + learning_rate*grad
        itr += 1
    return theta,error_list

In [47]:
final_theta,error = algo(X,Y)

In [44]:
final_theta

array([ 1.49138699, 29.84297081, 93.16540718,  8.32556432, 45.01071403,
        2.53283406])

In [45]:
error[-1]

array([332442.65243889])

# Testing Dataset

In [9]:
dataset_Test = pd.read_csv(r"Test.csv",encoding='utf-8')

In [10]:
X_test = dataset_Test.values[:,:5]
X_test = (X_test-X_test.mean())/X_test.std()
ones = np.ones((X_test.shape[0],1))
X_test = np.hstack((ones,X_test))

In [11]:
y_p=[]
for i in range(X_test.shape[0]):
    y_p.append(hypothesis(X_test[i],final_theta))
print(y_p)
y_p=[]
for i in range(X_test.shape[0]):
    y_p.append(hypothesis(X_test[i],final_theta))
print(y_p)


[113.14944409935616, 116.58799109592616, -23.54864830609636, -45.80668121434054, -97.92749139945555, -46.37877415613346, -77.52321148053176, 22.137218138200545, 172.56383324087926, 171.57512999186187, -107.44097144705074, -22.608242710824488, -5.6730548755287495, 121.58806281650413, 38.669565257907124, 44.089380779452505, -191.89856329220152, 20.925608261653025, 9.923965826283556, 134.9676796445417, 63.34554812744578, -63.907868106805644, -110.24101084750836, -9.181557819393497, -60.43381356325749, 10.172577454138583, 27.56890542779637, 106.23438660022119, 22.464134740150204, -27.925801347985537, 109.52389698092982, -46.75208270112013, 215.64653451353644, -15.647752799127232, -230.980338260052, 153.57253472899578, -3.9810148332040853, 11.008925714522015, -310.9040223350147, 75.57355578660481, -83.1801030215715, -208.94971723110635, -241.16795115831363, 133.37854750375683, -75.70317632614072, 104.00439992667395, -5.349680328888546, 18.911929355765025, -100.03710867348501, -29.3415734238

In [12]:
pd.DataFrame(y_p)

0
0    113.149444
1    116.587991
2    -23.548648
3    -45.806681
4    -97.927491
5    -46.378774
6    -77.523211
7     22.137218
8    172.563833
9    171.575130
10  -107.440971
11   -22.608243
12    -5.673055
13   121.588063
14    38.669565
15    44.089381
16  -191.898563
17    20.925608
18     9.923966
19   134.967680
20    63.345548
21   -63.907868
22  -110.241011
23    -9.181558
24   -60.433814
25    10.172577
26    27.568905
27   106.234387
28    22.464135
29   -27.925801
..          ...
370 -140.049709
371  -52.402627
372  -95.685831
373    7.091439
374  -16.393217
375  -64.773749
376  -18.259859
377 -175.186922
378 -124.878212
379   43.649223
380  -39.161506
381 -159.620124
382   85.989723
383   -2.070673
384  131.874905
385  -49.050881
386    0.832670
387  172.957147
388  169.650648
389   44.811868
390  -28.543132
391   58.047027
392  110.216832
393  -38.352124
394  -71.078079
395  -83.963332
396 -188.292727
397  123.887513
398   63.800380
399   55.467398

[400 rows x 1 columns]

In [13]:
import csv

In [14]:
with open('my_submission_3.csv','w', newline='') as f:
    fieldname = ['Id','target']
    thewriter = csv.DictWriter(f,fieldnames = fieldname)
    thewriter.writeheader()
    for i in range(X_test.shape[0]):
        thewriter.writerow({'Id':i,'target':str(y_p[i])})

# Score


In [15]:
from sklearn.metrics import r2_score

In [16]:
r2_score(Y_test,y_p)

NameError: name 'Y_test' is not defined

In [17]:
import matplotlib.pyplot as plt


In [ ]:
plt.grid()
plt.plot(error)
plt.show()

In [ ]:
m = X.shape[0]
n = X.shape[1]
indices = np.arange(m)
np.random.shuffle(indices)
indices = indices[:100]
print(indices)

# Batch Gradient Implementation 

In [28]:
def error_batch(X,Y,theta):
    m = X.shape[0]
    total_e = 0
    
    for i in range(m):
        h = hypothesis(X[i],theta)
        e = (Y[i] - h)**2
        total_e += e
        
    return total_e/(2*m)

def Batch_gradient(X,Y,theta,batch_size=10):
    grad = np.zeros((X.shape[1]))
    m = X.shape[0]
    n = X.shape[1]
    indices = np.arange(m)
    np.random.shuffle(indices)
    indices = indices[:batch_size]
    for j in range(n):
        for i in indices:
            hx = hypothesis(X[i],theta)
            grad[j] += ((Y[i] - hx)*X[i][j])
    return grad

def Batch_GradientDescent(X,Y,learning_rate = 0.001):
    theta = np.ones((X.shape[1]))
    itr = 0
    e = error_batch(X,Y,theta)
    error_list = [e]
    while(itr<X.shape[0]):
        grad = Batch_gradient(X,Y,theta)
        theta = theta + learning_rate*grad
        ne = error_batch(X,Y,theta)
        
        if(itr%10):
            error_list.append(ne)
            
        de = ne - e
        e = ne
        itr += 1
    return theta,error_list

In [29]:
theta_batch,error_batch = Batch_GradientDescent(X,Y)

In [25]:
theta_batch

array([ 1.49783934, 29.68792405, 93.34017939,  8.19302304, 43.71079479,
        2.87527813])

In [32]:
error_batch[-1]


array([207.88073814])

In [30]:
y_p=[]
for i in range(X_test.shape[0]):
    y_p.append(hypothesis(X_test[i],final_theta))
print(y_p)
y_p=[]
for i in range(X_test.shape[0]):
    y_p.append(hypothesis(X_test[i],final_theta))
print(y_p)


[113.14944409935616, 116.58799109592616, -23.54864830609636, -45.80668121434054, -97.92749139945555, -46.37877415613346, -77.52321148053176, 22.137218138200545, 172.56383324087926, 171.57512999186187, -107.44097144705074, -22.608242710824488, -5.6730548755287495, 121.58806281650413, 38.669565257907124, 44.089380779452505, -191.89856329220152, 20.925608261653025, 9.923965826283556, 134.9676796445417, 63.34554812744578, -63.907868106805644, -110.24101084750836, -9.181557819393497, -60.43381356325749, 10.172577454138583, 27.56890542779637, 106.23438660022119, 22.464134740150204, -27.925801347985537, 109.52389698092982, -46.75208270112013, 215.64653451353644, -15.647752799127232, -230.980338260052, 153.57253472899578, -3.9810148332040853, 11.008925714522015, -310.9040223350147, 75.57355578660481, -83.1801030215715, -208.94971723110635, -241.16795115831363, 133.37854750375683, -75.70317632614072, 104.00439992667395, -5.349680328888546, 18.911929355765025, -100.03710867348501, -29.3415734238

In [27]:
with open('my_submission_5.csv','w', newline='') as f:
    fieldname = ['Id','target']
    thewriter = csv.DictWriter(f,fieldnames = fieldname)
    thewriter.writeheader()
    for i in range(X_test.shape[0]):
        thewriter.writerow({'Id':i,'target':str(y_p[i])})